#pragma once
//#include "BaseComponent.h"
//Core Components
#include "InputComponent.h"
#include "TextureComponent.h"
#include "TransformComponent.h"
#include "InputComponent.h"
#include "TileComponent.h"
#include "CollisionComponent.h"
#include "SpriteComponent.h"
#include "NpcComponent.h"
#include "RenderComponent.h"
//Sub Components
#include "TextComponent.h"
#include "FPSComponent.h"
#include "MoveComponent.h"